apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cicd-platform
  namespace: argocd
spec:
  project: default
  
  # Where is the code?
  source:
    repoURL: https://github.com/Anubhav-singhx/cicd-platform.git  # REPLACE YOUR-USERNAME
    targetRevision: main
    path: helm-chart  # Changed from k8s to helm-chart
    helm:
      valueFiles:
        - values.yaml  # Base values
        - values-prod.yaml  # Production overrides
  
  # Where to deploy?
  destination:
    server: https://kubernetes.default.svc
    namespace: cicd-prod  # Changed from cicd-demo to cicd-prod
  
  # Auto-sync settings
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m